refactor

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -8,94 +8,112 @@ on:
     branches:
       - "*"
   workflow_dispatch:
+
 jobs:
-  build_docs_job:
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        include:
-         - os: linux.g5.4xlarge.nvidia.gpu
-           python-version: 3.8
-    container:
-      image: nvidia/cuda:12.0.1-runtime-ubuntu20.04
+  job:
+    name: build_docs_job
+    env:
+      DOCKER_IMAGE: nvidia/cudagl:11.4.2-runtime
+      REPOSITORY: pytorch/rl
+      SCRIPT: |
+        # Set env vars from matrix
+        export PYTHON_VERSION=${{ matrix.python_version }}
+        # Commenting these out for now because the GPU test are not working inside docker
+        export CUDA_ARCH_VERSION=${{ matrix.cuda_arch_version }}
+        export CU_VERSION="cu${CUDA_ARCH_VERSION:0:2}${CUDA_ARCH_VERSION:3:1}"
+        # Remove the following line when the GPU tests are working inside docker, and uncomment the above lines
+        #export CU_VERSION="cpu"
+
+        echo "PYTHON_VERSION: $PYTHON_VERSION"
+        echo "CU_VERSION: $CU_VERSION"
+
+        cd /work
+
+        ## setup_env.sh
+        ./.circleci/docs/setup_env.sh
+    runs-on: linux.g5.4xlarge.nvidia.gpu
+    timeout-minutes: 45
     steps:
-    - name: Check for dockerenv file
-      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
-    - name: check nvidia
-      run: |
-        pwd
-        nvidia-smi
-    - name: Install rsync 📚
-      run: |
-        apt-get update && apt-get install -y rsync
-    - name: Checkout
-      uses: actions/checkout@v3
-    # Update references
-    - name: Install deps
-      run: |
-        apt-get update && apt-get install -y git wget gcc g++
-    - name: Setup conda
-      run: |
-        root_dir="$(pwd)"
-        conda_dir="${root_dir}/conda"
-        env_dir="${root_dir}/env"
-        os=Linux
-        # 1. Install conda at ./conda
-        printf "* Installing conda\n"
-        wget -O miniconda.sh "http://repo.continuum.io/miniconda/Miniconda3-latest-${os}-x86_64.sh"
-        bash ./miniconda.sh -b -f -p "${conda_dir}"
-        eval "$(${conda_dir}/bin/conda shell.bash hook)"
-        printf "* Creating a test environment\n"
-        conda create --prefix "${env_dir}" -y python="$PYTHON_VERSION"
-        printf "* Activating\n"
-        conda activate "${env_dir}"
-    - name: Update pip
-      run: |
-        apt-get install python3.8 python3-pip -y
-        pip3 install --upgrade pip
-    - name: check python version
-      run: |
-        python3 --version
-    - name: Check git version
-      run: git version
-    - name: Install PyTorch
-      shell: bash
-      run: |
-        pip3 install --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu118 --quiet --root-user-action=ignore
-    - name: Install tensordict
-      run: |
-        pip3 install git+https://github.com/pytorch-labs/tensordict.git --quiet --root-user-action=ignore
-    - name: Install TorchRL
-      run: |
-        pip3 install -e . --quiet --root-user-action=ignore
-    - name: Install requirements
-      run: |
-        pip3 install -r docs/requirements.txt --quiet --root-user-action=ignore
-    - name: Test torchrl installation
-      shell: bash
-      run: |
-        mkdir _tmp
-        cd _tmp
-        PYOPENGL_PLATFORM=egl MUJOCO_GL=egl python3 -c """from torchrl.envs.libs.dm_control import DMControlEnv
-        print(DMControlEnv('cheetah', 'run').reset())"""
-        cd ..
-    - name: Build the docset
-      id: build_doc
-      run: |
-        cd ./docs
-        #timeout 7m bash -ic "MUJOCO_GL=egl sphinx-build ./source _local_build" || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
-        PYOPENGL_PLATFORM=egl MUJOCO_GL=egl sphinx-build ./source _local_build
-        cd ..
-    - name: Pull TensorDict docs
-      run: |
-        git clone --branch gh-pages https://github.com/pytorch-labs/tensordict.git docs/_local_build/tensordict
-        rm -rf docs/_local_build/tensordict/.git
-    - name: Get output time
-      run: echo "The time was ${{ steps.build.outputs.time }}"
-    - name: Deploy
-      if: ${{ github.ref == 'refs/heads/main' }}
-      uses: JamesIves/github-pages-deploy-action@releases/v4
-      with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          branch: gh-pages # The branch the action should deploy to.
-          folder: docs/_local_build/ # The folder the action should deploy.
+      - name: Clean workspace
+        run: |
+          echo "::group::Cleanup debug output"
+          sudo rm -rfv "${GITHUB_WORKSPACE}"
+          mkdir -p "${GITHUB_WORKSPACE}"
+          echo "::endgroup::"
+
+      - name: Install rsync 📚
+        run: |
+          apt-get update && apt-get install -y rsync
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Linux
+        uses: pytorch/test-infra/.github/actions/setup-linux
+
+      - name: Setup SSH
+        uses: pytorch/test-infra/.github/actions/setup-ssh
+        with:
+          github-secret: ${{ github.token }}
+
+      - name: Pull docker image
+        uses: ./test-infra/.github/actions/pull-docker-image
+        with:
+          docker-image: ${{ env.DOCKER_IMAGE }}
+
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Run script in container
+        continue-on-error: ${{ inputs.continue-on-error }}
+        working-directory: ${{ inputs.repository }}
+        run: |
+          set -ex
+          {
+            echo "#!/usr/bin/env bash";
+            echo "set -eou pipefail";
+            # shellcheck disable=SC2016
+            echo 'eval "$(conda shell.bash hook)"';
+            echo "${SCRIPT}";
+          } > "${RUNNER_TEMP}/exec_script"
+          chmod +x "${RUNNER_TEMP}/exec_script"
+          # detached container should get cleaned up by teardown_ec2_linux
+          # shellcheck disable=SC2086,SC2090
+          container_name=$(docker run \
+            -e RUNNER_ARTIFACT_DIR=/artifacts \
+            --env-file="${RUNNER_TEMP}/github_env_${GITHUB_RUN_ID}" \
+            `# It is unknown why the container sees a different value for this.` \
+            --env=GITHUB_STEP_SUMMARY \
+            --cap-add=SYS_PTRACE \
+            --detach \
+            --ipc=host \
+            --security-opt seccomp=unconfined \
+            --shm-size=2g \
+            --tty \
+            --ulimit stack=10485760:83886080 \
+            ${GPU_FLAG:-} \
+            -v "${GITHUB_WORKSPACE}/${REPOSITORY}:/work" \
+            -v "${GITHUB_WORKSPACE}/test-infra:/test-infra" \
+            -v "${RUNNER_ARTIFACT_DIR}:/artifacts" \
+            -v "${RUNNER_TEMP}/exec_script:/exec" \
+            -v "${GITHUB_STEP_SUMMARY}":"${GITHUB_STEP_SUMMARY}" \
+            -w /work \
+            "${DOCKER_IMAGE}"
+          )
+          docker exec -t "${container_name}" bash /exec
+
+      - name: Pull TensorDict docs
+        run: |
+          git clone --branch gh-pages https://github.com/pytorch-labs/tensordict.git docs/_local_build/tensordict
+          rm -rf docs/_local_build/tensordict/.git
+
+      - name: Deploy
+        if: ${{ github.ref == 'refs/heads/main' }}
+        uses: JamesIves/github-pages-deploy-action@releases/v4
+        with:
+            token: ${{ secrets.GITHUB_TOKEN }}
+            branch: gh-pages # The branch the action should deploy to.
+            folder: docs/_local_build/ # The folder the action should deploy.
+
+      - name: Teardown Linux
+        if: ${{ always() }}
+        uses: ./test-infra/.github/actions/teardown-linux
